BoardView:
  boardExists: "A board with this name already exists."
  boardTooHigh: "Board altitude is too high - roof would be above top of world."
  boardWouldIntersect: "Board would intersect existing board {0}."
  noFreeBoards: "There are no free boards to create a game on."
  noSuchBoard: "No such board {0}."

ChessAI:
  AIbusy: "AI is busy right now"
  AIdisabled: "AI games are disabled"
  AIloadError: "AI Loading Error"
  AInotFound: "AI not found"
  AIunexpectedException: "Unexpected Exception in AI: {0}"
  computer: "Computer"
  human: "Human"
  noAvailableAIs:
    - "There are no AIs available to play right now"
    - "(all {0,number,integer} are currently in a game)."
  noFreeAI: "No free AI was found"

ChessCommandExecutor:
  activeGameChanged: "Your active game is now &6{0}&-."
  activeGameIs: "Your active game is &6{0}&-."
  AIdefsReloaded: "AI definitions have been reloaded."
  AIList: "&6{0}&- ({1})&- {2}"
  AIpayout: "payout={0,number,integer}%"
  algebraicNotation: "&5 (standard algebraic notation)"
  allBoardsRedrawn: "All boards have been redrawn."
  boardCantBeDeleted: "Can''t delete board &6{0}&- - it is being used by game &6{1}&-."
  boardCreationPrompt:
    - "Left-click a block: create board &6{0}&-. Right-click: cancel."
    - "This block will become the centre of the board's A1 square."
  boardDeleted: "Deleted board &6{0}&-."
  boardDetail:
    board: "Chessboard &6{0}:"
    boardStyle: "Board Style: &f{0}"
    enclosure: "Enclosure: &f{0}"
    frameWidth: "Frame width: &f{0,number,integer} ({1})"
    game: "Game: &f{0}"
    height: "Height: &f{0,number,integer}"
    lightLevel: "Light level: &f{0,number,integer}"
    boardExtents: "Board Extents: &f{0} - {1}"
    pieceStyle: "Piece Style: &f{0}"
    squareSize: "Square size: &f{0,number,integer} ({1}/{2})"
    struts: "Enclosure struts: &f{0}"
    boardOrientation: "Board Orientation: &f{0}"
    defaultStake: "Default Stake: &f{0} {1}"
    defaultTimeControl: "Default Time Control: &f{0} {1}"
    locked: (locked)
    teleportDest: "Teleport-out destination: &f{0}"
  boardList: "&6{0}&-: loc=&f{1}&- style=&6{2}&- game=&6{3}&-"
  boardRedrawn: "Board &6{0}&- has been redrawn."
  boardStyleChanged: "Board &6{0}&- style changed."
  boardStyleSuggestSave: "Use &f/chess board save [<new-style-name>]&- to save changes."
  boardStyleSaved: "Board &6{0}&- style saved as &6{1}&-."
  boardStyleBadParam: "Invalid style parameter value &6{0}&-."
  boardTeleportSet: "The teleport-out destination has been set for board &6{0}&-."
  boardTeleportCleared: "The teleport-out destination has been cleared for board &6{0}&-."
  cantAffordStake: "You can't afford that stake!"
  canTeleport: "You can teleport to your game with &f/chess tp {0}"
  chessSaved: "Chess boards and games have been saved."
  configKeySet: "{0} is now set to: {1}"
  configReloaded: "Configuration (config.yml) has been reloaded"
  designMode: "Board is in design mode (set &6{0}&-)."
  drawOfferedOther: "&6{0}&- has offered a draw."
  drawOfferedYou: "You have offered a draw to &6{0}&-."
  gameCreated:
    - "Game &6{0}&- has been created on &6{1}&-."
    - "Now type (or use control panel buttons):"
    - "&5‣&- &f/chess invite <playername>&- to invite someone"
    - "&5‣&- &f/chess invite&- to create an open invitation"
    - "&5‣&- just &f/chess start&- to play a random AI opponent"
  gameDeleted: "Game &6{0}&- has been deleted."
  gameDeletedAlert: "Game deleted by &6{0}&-!"
  gameDetail:
    blackToPlay: "&8Black&- to play"
    clock: "Clock: &fWhite&-: {0}, &8Black&-: {1}"
    invitation: "&6{0}&- has been invited.  Awaiting response."
    moveHistory: "&eMove history:"
    name: "&eGame {0} [{1}]:"
    openInvitation: "Game has an open invitation"
    players: "&6{0}&- (&fWhite&-) vs. &6{1}&- (&8Black&-) on board &6{2}&-."
    stake: "&eStake: &f{0}"
    whiteToPlay: "&fWhite&- to play"
    halfMoves: "&f{0,number,integer}&- half-moves made"
    timeControlType: "&eTime Control: &f{0}"
  globalTeleportSet: "The global teleport-out destination has been set."
  globalTeleportCleared: "The global teleport-out destination has been cleared."
  goingToSpawn: "Can't find a safe place to send you - going to spawn point."
  invalidFromSquare: "Invalid FROM square in {0}"
  invalidMoveString: "Invalid move string {0}"
  invalidNumeric: "Invalid numeric value: {0}"
  invalidToSquare: "Invalid TO square in {0}"
  invited: " invited: &6{0}&-"
  joinedGame: "You have joined the chess game &6{0}&- as &f{1}&-."
  needToWait: "You need to wait {0,number,integer} seconds more."
  noActiveGame: "You have no active game. Use &f/chess game <name>&- to set one."
  noBoards: "There are currently no boards."
  noCurrentGames: "There are currently no games."
  noGame: "(none)"
  noPendingInvitation: "You don't have any pending invitations right now."
  noTeleporting: "Teleporting to or from boards is not permitted right now."
  notFromConsole: "This command cannot be run from the console."
  notOnChessboard: "Not on a chessboard!"
  otherPlayerMustBeOffline: "You can only do this if the other player has gone offline."
  persistedReloaded: "Persisted board and game data has been reloaded."
  PGNarchiveWritten: "Wrote PGN archive to {0}"
  positionUpdatedFEN:
    - "Game position for &6{0}&- has been updated. {1} to play."
    - "&4NOTE: &-move history invalidated, this game can no longer be saved."
  promotionPieceSet: "Promotion piece for game &6{0}&- has been set to &6{1}&-."
  sanNotation: "&5 (SAN notation)"
  scoreRecord: "&e{0,number,integer}) &6{1}&-: &f{2}&-"
  sideSwapOfferedOther: "&6{0}&- has offered to swap sides."
  sideSwapOfferedYou: "You have offered to swap sides with &6{0}&-."
  stakeChanged: "Stake for this game is now {0}."
  undoOfferedOther: "&6{0}&- wishes to undo their last move."
  undoOfferedYou: "You have asked &6{0}&- if you may undo your last move."
  undoAIWithStake: "You may not undo moves when playing for a stake against the computer."
  stakeChanged: "Stake for this game is now {0}."
  teleportDestObstructed: "Teleport destination obstructed!"
  timeControlSet: "Time control for this game set to {0} ({1})"
  timeControlsReloaded: "Time control definitions have been reloaded."
  typeYesOrNo: "Type &f/chess yes&- to accept, or &f/chess no&- to decline."

ChessConfig:
  invalidBoolean: "Invalid boolean value: {0} (use true/yes or false/no)"
  invalidInteger: "Invalid integer value: {0}"
  invalidFloat: "Invalid floating-point value: {0}"
  invalidDuration: "Invalid duration: {0}"
  noSuchKey: 
    - "No such configuration key: {0}"
    - "Use &f/chess getcfg&- to list all valid keys"
 
ChessEntityListener:
  goingToSpawn: "Can't find a safe place to displace you - going to spawn."

ChessPlayerListener:
  boardCreationCancelled: "Board creation cancelled."
  currentGames: "Your current chess games: {0}"
  moveCancelled: "Move cancelled."
  pieceSelected: "&f{0}&- at &f{1}&- selected. Left-click to move it."
  playerBack: "{0} is back in the game!"
  playerInviteCancelled: "&6Player invitation cancelled."
  playerQuit: "{0} quit.  If they don''t rejoin within {1,number,integer} seconds, you can type &f/chess win&- to win by default."
  squareMessage: "Square &6[{0}]&-, board &6{1}"
  youPlayed: "You played &f{0}&-."

ChessUtils:
  bishop: "Bishop"
  king: "King"
  knight: "Knight"
  pawn: "Pawn"
  queen: "Queen"
  rook: "Rook"
  anything: "anything"

# Button text definitions may contain a semicolon (;).  This indicates a line break on the sign text.
ControlPanel:
  acceptDrawBtn: "Accept Draw?"
  acceptSwapBtn: "Accept Swap?"
  acceptUndoBtn: "Accept Undo?"
  blackPawnPromotionBtn: "Black Pawn;Promotion"
  boardInfoBtn: ";Board;Info"
  chessInviteReminder: "Type &f/chess invite <playername>&- to invite someone"
  chessInvitePrompt: "Type a player name to invite.  Left or right-click cancels."
  createGameBtn: ";Create;Game"
  gameInfoBtn: ";Game;Info"
  halfmoveClock: "Halfmove;Clock"
  inviteAnyoneBtn: ";Invite;ANYONE"
  invitePlayerBtn: ";Invite;Player"
  noBtn: ";;No"
  offerDrawBtn: ";Offer;Draw"
  playNumber: "Play Number"
  resignBtn: ";Resign"
  stakeBtn: "Stake;;"
  startGameBtn: ";Start;Game"
  teleportOutBtn: ";Teleport;Out"
  timeControl: "Time Control"
  timeElapsed: "Elapsed"
  timeRemaining: "Remaining"
  undoBtn: ";Undo;Last Move"
  whitePawnPromotionBtn: "White Pawn;Promotion"
  yesBtn: ";;Yes"

Designer:
  inDesignMode: "Board &6{0}&- is now in design mode."
  outOfDesignMode: "Board &6{0}&- is now out of design mode."
  styleSaved:
    - "Custom piece style &6{0}&- saved."
    - "Use &f/chess board set piecestyle {0}&- while standing on a suitable board to use it."
  styleLoaded:
    - "Piece style &6{0}&- loaded.  You can make changes now."
    - "Use &f/chess design save [<new-style-name>] to save it."
  mustBeInDesignMode: "You must be in design mode first.  Use &f/chess design&-."
  gameRunning: "You cannot design on a board with a game in progress."
  notOnBoard: "You are not standing on a chess board."
  cleared: "The current piece design has been cleared."
  
ExpectBoardCreation:
  boardCreated: "Board &6{0}&- has been created at {1}."

ExpectYesNoOffer:
  drawOfferAccepted: "Your draw offer has been accepted by &6{0}&-."
  drawOfferDeclined: "Your draw offer has been declined by &6{0}&-."
  undoOfferAccepted: "Your undo offer has been accepted by &6{0}&-."
  undoOfferDeclined: "Your undo offer has been declined by &6{0}&-."
  swapOfferAccepted: "Your swap offer has been accepted by &6{0}&-."
  swapOfferDeclined: "Your swap offer has been declined by &6{0}&-."
  youDeclinedDrawOffer: "You have declined the draw offer."
  youDeclinedSwapOffer: "You have declined the swap offer."
  youDeclinedUndoOffer: "You have declined the undo offer."

Flight:
  flightEnabled:
    - You are close enough to a chess board to fly.
    - Double-tab Space to toggle flight.
  flightDisabled: You are no longer close enough to a chess board to fly.
  flightDisabledByAdmin: Chess board flight has been disabled by a server admin.
  interactionStopped: You may not interact with the world while flying around a chess board!
  
Game:
  boardAlreadyHasGame: "That board already has a game on it."
  boardInDesignMode: "That board is being used for piece designing."
  sitePGN: " in Minecraftia"
  AIisBusy: "That AI is currently busy playing a game."
  alertPrefix: "&6♚ &-Game &6{0}&-: "
  archiveExists: "Archive file {0} exists - won''t overwrite."
  abandoned: "&6{0}&- drew with &6{1}&- (game abandoned) in a game of Chess!"
  autoDeleteFinished: "Finished game auto-deleted."
  autoDeleteNotStarted: "Game auto-deleted (not started within {0})."
  autoDeleteRunning: "Game auto-deleted (no move made within {0})."
  black: "Black"
  cantAffordToStart: "{0} can''t afford to play! (need {1})"
  cantAffordToJoin: "You can''t afford the stake for this game (need {0})!"
  cantWriteArchive: "Can''t write PGN archive {0}: {1}"
  check: " &5+++&dYou are in Check&5+++"
  checkmated: "&6{0}&- checkmated &6{1}&- in a game of Chess!"
  drawAgreed: "&6{0}&- drew with &6{1}&- (draw agreed) in a game of Chess!"
  fiftyMoveRule: "&6{0}&- drew with &6{1}&- (50-move rule) in a game of Chess!"
  forfeited: "&6{0}&- beat &6{1}&- (forfeited) in a game of Chess!"
  gameHasStake: "This game has a stake of &f{0}&-."
  gameIsFull: "This game already has two players."
  getStakeBack: "You get your stake of {0} back."
  invalidPromoPiece: "Invalid promotion piece: {0}."
  inviteCooldown: "You must wait {0,number,integer} seconds before sending another open invitation."
  inviteSent: "An invitation has been sent to &6{0}&-."
  inviteWithdrawn: "Your invitation has been withdrawn."
  joinPrompt: "Type &f/chess join&- to join the game."
  joinPromptGlobal: "Type &f/chess join {0}&- to join the game."
  lostStake: "You lost your stake of {0}."
  moveUndone: "The last move has been undone.  &f{0}&- to play."
  newTimeControlPhase: "New time control phase started: &6{0}&-."
  noActiveGame: "No active game - set one with &f/chess game <name>&-."
  noNegativeStakes: "Negative stakes are not permitted!"
  noSuchGame: "No such game &6{0}&-."
  notInGame: "You are not in this game!"
  notInvited: "You don't have an invitation for this game."
  notStarted: "The game has not yet started."
  notYourTurn: "It is not your turn."
  nowPlayingBlack: "Side swap!  You are now playing Black."
  nowPlayingWhite: "Side swap!  You are now playing White."
  openInviteCreated: "&6{0}&e has created an open invitation to a chess game."
  paidStake: "You have paid a stake of {0}."
  playerJoined: "&6{0}&- has joined your game."
  playerNotOnline: "Player {0} is not online."
  playerPlayedMove: "{0} played [&f{1}&-].  Your move."
  resigned: "&6{0}&- beat &6{1}&- (resigned) in a game of Chess!"
  shouldBeState: "Game should be in state {0}."
  stakeCantBeChanged: "Stake cannot be changed once both players have joined."
  stakeLocked: "The stake for this game is locked and may not be changed."
  stakeTooHigh: "The maximum stake allowed is {0,number,currency}."
  stalemated: "&6{0}&- drew with &6{1}&- (stalemate) in a game of Chess!"
  started:
    - "Game started!  You are playing &f{0}&-."
    - "To move a piece, look at it while holding {1}, and left-click."
  startPrompt: "Start the game by typing &f/game start&-."
  timeControlLocked: "The time control for this game is locked may not be changed."
  timeControlWarning: "You have {0,number,integer} seconds left to move!"
  white: "White"
  youAreInvited: "You have been invited to this game by &6{0}&-."
  yourMove: "It is your move &f({0})&-."
  youWon: "You have won {0}!"

MessageBuffer:
  header: "| {0,number,integer}-{1,number,integer} of {2,number,integer} lines (page {3,number,integer}/{4,number,integer}) |"
  footer: "| Use /chess page [#|n|p] to see other pages |"

# these messages need to be 15 characters max. (including colour codes) because they are displayed on signs
SMSIntegration:
  boardInfo: "&1Board Info"
  createGame: "&1Create Game"
  gotoGame: "&1Go to Game"
  gameInfo: "&1Game Info"
  deleteGame: "&4*Delete Game"
  gotoBoard: "&1Go to Board"

TerrainBackup:
  cantDeleteTerrain: "Could not delete {0}"
  cantRestoreTerrain: "Terrain backup could not be restored: {0}"
  cantWriteTerrain: "Terrain backup could not be written: {0}"
