default:
  starting: true
  spawns:[]
  time: 22
  duration: 200
  int: 30
  bigint: 6000
  fireworks:
    t1:
    - ???:???:???
    t2:
    - ???:???:???
    t3:
    - ???:???:???
    t4:
    - ???:???:???
    t6:
    - ???:???:???
    t7:
    - ???:???:???
    t8:
    - ???:???:???
